#pragma once
#include "PVP.h"
#include "Global.h"
#include <EventAPI.h>
#include <TranslationAPI.h>
#include <SendPacketAPI.h>
#include <MC/Level.hpp>
#include <MC/Player.hpp>
#include <MC/ActorDamageSource.hpp>